<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-N054NMB" failures="2" tests="9" name="RetryMultipleFailedTestCases" time="0.133" errors="0" timestamp="2021-10-25T21:37:45 IST">
  <testcase classname="com.test.TestNgRetryLogicFeature" name="test1" time="0.014">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="com.test.TestNgRetryLogicFeature" name="test1" time="0.003">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="com.test.TestNgRetryLogicFeature" name="test1" time="0.001">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="com.test.TestNgRetryLogicFeature" name="test1" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.test.TestNgRetryLogicFeature.test1(TestNgRetryLogicFeature.java:10)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="com.test.TestNgRetryLogicFeature" name="test2" time="0.003">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="com.test.TestNgRetryLogicFeature" name="test2" time="0.006">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="com.test.TestNgRetryLogicFeature" name="test2" time="0.002">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="com.test.TestNgRetryLogicFeature" name="test2" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.test.TestNgRetryLogicFeature.test2(TestNgRetryLogicFeature.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="com.test.TestNgRetryLogicFeature" name="test3" time="0.002"/>
</testsuite> <!-- RetryMultipleFailedTestCases -->
